### ISSUE TITLE
此项目还在维护吗

### ISSUE THREAD

**Issue by threerog** [endink/Thrifty#4]
作者您好
很幸运能在github搜索中看到国人开源的thrift相关的项目
想咨询一下当前项目还在维护中吗，或者有考虑支持到net5/6 tfm
以及开发文档中提到的idl转换器还在计划中吗

**Comment by threerog** [comment]
有没有thrift序列化和反序列化的静态方法支持，我只需要向json一样序列化和反序列化对象就行了，不涉及网络请求
我看了下代码好像没找到，只找到个一个services里的面向对象序列化的，不知道是不是同样的功能

**Comment by threerog** [comment]
能提供一个联系方式吗
准备直接找您基于Thrifty开发项目

**Comment by endink** [comment]
@threerog 不好意思，因为日常使用java,这只是很久以前为了和java兼容的类库，该库经过严格的单元测试和集成测试，库本身没有问题，序列化方法你也可以轻松提取，个人精力有限，无法提供一对一支持，实在抱歉

**Comment by endink** [comment]
@threerog 序列化的核心代码请参考 ThriftCodecManager 类

**Comment by threerog** [comment]
暂时没有精力接商业项目开发吗，换个联系方式聊吧，这上面聊太难受了
我的微信号poprog
邮箱threerog@qq.com

**Comment by threerog** [comment]
仍然有两个问题期待回复 万分感谢
我目前采用的是`TCompactProtocol`，`thrifty`主要用于组包解包，网络请求由其他程序完成
1.如何反序列化带有`TMessage`的bytes，因为程序提交过来的数据就是完整的thrift传输数据(`TMessage+Obj`)，我尝试直接反序列化失败，但把`TMessage`相关的bytes去除后就能成功反序列化至目标对象，但是`TMessage`可能长度不能固定(`seqId`)，不知道如何快速反序列化到对象。

2.如何序列化对象时带有TMessage=>`TMessage+Obj`，便于其他程序直接请求而不关心组包的问题，我尝试在对象类里添加`TMessageField`，但是序列化失败 提示不是c#类型

```
var request = new byte[]{0x82, 0x21, 0x0, 0xb, 0x6f, 0x70, 0x65, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1c, 0x1b, 0x0, 0x0, 0x0};

struct OpenSessionRequest{
      1: map<string,string> metaData;
}
```

```
var response = new byte[]{0x82, 0x41, 0x0, 0xb, 0x6f, 0x70, 0x65, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x8, 0x0, 0x20, 0x48, 0x68, 0x6c, 0x36, 0x4f, 0x6a, 0x63, 0x79, 0x69, 0x74, 0x65, 0x4a, 0x46, 0x45, 0x68, 0x64, 0x39, 0x64, 0x53, 0x61, 0x45, 0x4e, 0x57, 0x39, 0x59, 0x41, 0x32, 0x64, 0x63, 0x54, 0x66, 0x6e, 0x0};

struct OpenSessionResponse{
      1: string authSessionId;
}
```

**Comment by threerog** [comment]
我愿意支付2k赞助此开源项目
期待获得`Author`的进一步指导，当然将我的项目直接付费委托`Author`开发最好
盼复
