### ISSUE TITLE
1

### ISSUE THREAD

**Issue by threerog** [endink/Thrifty#5]

**Comment by endink** [comment]
你可以运行单元测试检查项目是否正常，这个项目在当时是 Production ready 的，序列化有专门的 Unit Test case ，方便你了解其中原理。

**Comment by endink** [comment]
BTW， 如果你没有跨语言需求，只是想简单的使用一个高效的序列化方案，我推荐你看看 Protosfuff ，MessagePack ，Arvo 这些项目

**Comment by endink** [comment]
参考这个 [单元测试类](https://github.com/endink/Thrifty/blob/master/test/Swifty.Tests/Services/Codecs/Internal/Reflection/ReflectionThriftStructCodecTest.cs)
